spring:
  datasource:
    url: jdbc:mysql:///studb
    username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: stu_provider
  registry:
    address: zookeeper://172.18.224.208:2181
